server:
  port: 9999
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.127.155:8848
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
    gateway:
      routes:
        #类别路由转发
        - id: categories_route
          uri: lb://categories
          predicates:
            - Path=/admin/categories/**
          filters:
            - StripPrefix=1

        - id: users_route
          uri: lb://users
          predicates:
            - Path=/admin/users/**
          filters:
            - StripPrefix=1

        - id: videos_route
          uri: lb://videos
          predicates:
            - Path=/admin/videos/**
          filters:
            - StripPrefix=1

      globalcors:
        cors-configurations:
          '[/**]':  #所有的路径
            allowedOrigins: "*"  #配置前台APP地址
            allowedMethods: "*"  #配置请求方式  GET POST DELETE
            AllowedHeaders: "*"  #配置请求头



